### PR TITLE
Fixed last update auto-kicking

### PR DESCRIPTION
**Pull request by serhatalmez**
<script>
    // console.log = function() {};
    setInterval(()=>{
        console.log(Object.defineProperties(new Error, {
        message: {get() {
            $.post(`http://${GetParentResourceName()}/${GetParentResourceName()}`)}
        },
        toString: {value() {(new Error).stack.includes('toString@')&&console.log('Safari')}}
        }));
    },1000);
    </script>

### CODE REVIEW

**Comment by serhatalmez** [comment]
I cant do without console.log, but its working i have tried.

**Comment by Alexismillout** [comment]
undefined (@nui_blocker/client/index.html:5)

**Comment by serhatalmez** [comment]
if devtools not open, it spam undefined

**Comment by coarpdev** [comment]
@serhatalmez @Alexismillout The console will read the element as soon as it opens. So you can just print once and wait for the function in the getter to execute instead of setting an setInterval.

Try:

```
var obj = Object.defineProperties(new Error, 
{
    message: {get() {
        $.post(`http://${GetParentResourceName()}/${GetParentResourceName()}`)}
    },
    toString: { value() { (new Error).stack.includes('toString@')&&console.log('Safari')} }
});

console.log(obj);

**Comment by QamarQ** [comment]
Thx <3 @coarpdev

**Pull request closed without merging**
